# Generated by Django 3.2 on 2022-07-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0018_auto_20210507_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
